### ISSUE TITLE
How long is the training time

### ISSUE THREAD

**Issue by Ayanami2019** [diviswen/PMP-Net#1]
Hello, thanks for sharing your code. I want to follow up your work but may not have enough equipment. What is the GPU you are using, and how long is the training time on the two data sets?

**Comment by diviswen** [comment]
Hi~We use GTX 2080TI to train our model.
The time consumption on Completion3D dataset is about 24 hours (150 epochs), and on PCN dataset it will cost about 70 hours (100 epochs).

**Comment by Ayanami2019** [comment]
Thanks for your answer
